apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdep
  namespace: sivans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcon
        image: sivane/java-repo-cicdscr:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
  namespace: sivans
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
